name: Test Omarchy Installation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run Docker-based test
      run: |
        cd tests
        chmod +x docker-test.sh
        ./docker-test.sh 